

## Classes:

Create a class in Python to represent fractions. The internal representation contains two integers (the numerator and denominator). 

The functions in the class should include:
   * multiplication (a/b * c/d)
   * print the fraction (in the form a/b) (hint: use \__str__ function)
   * invert the fraction (a/b becomes b/a)

#### Example usage of this class:

frac = Fraction(3, 4) # Fraction 3/4

frac2 = Fraction(4, 3) # Fraction 4/3

frac.multiply(frac2)

print(frac)

frac.invert()

In [2]:
def gcd(m,n):
    while m%n != 0:
        oldm = m
        oldn = n

        m = oldn
        n = oldm%oldn
    return n

class Fraction:
     def __init__(self,top,bottom):
         self.num = top
         self.den = bottom

     def __str__(self):
         return str(self.num)+"/"+str(self.den)

     def show(self):
         print(self.num,"/",self.den)

     def __mul__(self,otherfraction):
         newnum = self.num*otherfraction.num
         newden = self.den * otherfraction.den
         common = gcd(newnum,newden)
         return Fraction(newnum//common,newden//common)

     def __eq__(self, other):
         firstnum = self.num * other.den
         secondnum = other.num * self.den

         return firstnum == secondnum
     def invert(fraction):
         return Fraction(fraction.den,fraction.num)
x = Fraction(1,2)
y = Fraction(2,3)
print(x*y)
z=Fraction.invert(Fraction(3,5))
print(z)


1/3
5/3


## Numpy:

In [3]:
# Get a list of integers as input from the user and convert it into a numpy array.
import numpy as np
list=[]
n=int(input("enter number of elements"))
for i in range(n):
    ele=int(input())
    list.append(ele)
a=np.array(list)
print(a)


enter number of elements5
2
3
4
5
6
[2 3 4 5 6]


In [4]:
# Create an array of ones (all elements in the array is one) of shape (4, 5) [three rows and 5 columns]. 
import numpy as np
np.ones((4,5),dtype=int)


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [5]:
'''
Given the following array,

X = [[2, 5]
    [1, 5],
    [0, 7]]
    
Write numpy slicing code to get the following as output:

1. [2, 1, 0]
2. [1, 5]
3. 7
4. [2, 7, 0]  (hint, use a list of indices)

'''



'\nGiven the following array,\n\nX = [[2, 5]\n    [1, 5],\n    [0, 7]]\n    \nWrite numpy slicing code to get the following as output:\n\n1. [2, 1, 0]\n2. [1, 5]\n3. 7\n4. [2, 7, 0]  (hint, use a list of indices)\n\n'

In [6]:
a=np.array([[2, 5],
           [1, 5],
           [0, 7]])
a[ :,0]

array([2, 1, 0])

In [8]:
a[1,:]

array([1, 5])

In [9]:
a[2,1]

7

In [10]:
# Create a numpy array and print its shape, dimensions, size and datatype
import numpy as np
n = np.array([1,6,4,9,3])
n.shape


(5,)

In [11]:
n.size

5

In [12]:
n.dtype

dtype('int32')

In [13]:
n.ndim

1

In [15]:
# Create a copy of a numpy array using .copy(), change the copy's value and print both arrays
x=np.ones((4,5),dtype=float)
y=x
y[:,2]=0
print(x)


[[1. 1. 0. 1. 1.]
 [1. 1. 0. 1. 1.]
 [1. 1. 0. 1. 1.]
 [1. 1. 0. 1. 1.]]


In [16]:
# Create a numpy array of size 15 and print all possible reshaping.

a=np.array([[1,2,3,4,5],
          [4,5,6,7,8],
          [7,8,9,5,4]])
a.reshape((5,3))

array([[1, 2, 3],
       [4, 5, 4],
       [5, 6, 7],
       [8, 7, 8],
       [9, 5, 4]])

In [17]:
a.reshape((1,15))

array([[1, 2, 3, 4, 5, 4, 5, 6, 7, 8, 7, 8, 9, 5, 4]])

In [18]:
a.reshape((15,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [4],
       [5],
       [6],
       [7],
       [8],
       [7],
       [8],
       [9],
       [5],
       [4]])

In [24]:
# Create a random array of shape (3, 4) and find the maximum in it
# hint : np.random.randint(0, 100, size=(3, 4))
a=np.array(np.random.randint(0,100,size=(3,4)))
print(a)
np.amin(a)

[[83  0 17 98]
 [36 28 74 40]
 [64 25 68 96]]


0

In [25]:
# Sort the following array:
# x = np.array([2, 1, 4, 3, 5])
x = np.array([2, 1, 4, 3, 5])
x.sort()
print(x)


[1 2 3 4 5]


In [30]:
# find the maximum element in each column of the folling array
# a = np.array([[1,2,4,7], [9,88,6,45], [9,76,3,4]])
A = np.array([[1,2,4,7], [9,88,6,45], [9,76,3,4]])
for i in range(len(A[i])):
    max_elm_col = np.amax(A[0:,i], axis=0)
    print(max_elm_col)

9
88
6
45


In [27]:
# Try adding an array of shape (3,4) and another array of shape (3,1)
a=np.array(np.random.randint(0,100,size=(3,4)))
b=np.array(np.random.randint(0,100,size=(3,1)))
c=np.append(a,b)
print(c)


[66 96 73 37 59 81 48 94 72 82 25 31 26 82 98]


In [28]:
# Try adding an array of shape (5,) and (,5)
import numpy as np
a=np.array(np.random.randint(0,100,size=(5,)))
b=np.array(np.random.randint(0,1000,size=(5,))).reshape((1,-1))
c=np.append(a,b)
print(c)


[ 55  78   8  25  35 847 521 629 501 274]


In [29]:
# Try adding two arrays of shape (3,3) and (2,2) each
a=np.array(np.random.randint(0,100,size=(3,3)))
b=np.array(np.random.randint(0,100,size=(2,2)))
c=np.append(a,b)
print(c)


[11 64 95 50 14 93 11 85 70 56 19 52 61]


### That's it folks