In [1]:
# Procedural code

def simple_interest(p, r, t):
    return(p*r*t/100)

def compound_interest(p, r, t):
    return(p*pow(1+(r/100), t))

p = 100

compound_interest(p, 7, 10)

196.71513572895665

In [2]:
# OOPs code

class loan():
    def __init__(self):
        self.principle = 100
    def compound_interest(self, r, t):
        return(self.p*pow(1+(r/100), t))
    
a = loan()
b = loan()
# a = dict()
# a = list()
a.compound_interest(7, 10)

196.71513572895665

In [6]:
a = int(10)
print(type(a))

c = list()
c.append(10)

<class 'int'>


## Classes

A class is a kind of data type, just like a string, integer or list. When we create an object of that data type, we call it an instance of a class.

Each class has a separate environment (no collision on function names)

In Python, everything is an object – everything is an instance of some class. 

In [112]:
sample = list()  # c = Coordinate(3, 4)
sample2 = [1, 2, 3]   # zero = Coordinate(0,0)
sample.append(sample2)  # c.distance(zero)

In [116]:
list.append(sample, sample2)

In [118]:
Coordinate.distance(c, zero)

5.0

In [119]:
Coordinate.__init__(c, 3, 4) # the reason for self

In [117]:
print(sample)

[[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]]


In [27]:
class Coordinate():
    
    this_is_global = 100 # all instances of the class share this variable
    
    def __init__(self, abc, y): # different instances will have diff values
        self.x = abc
        self.y = y
        
    def distance(self, other):
        x_diff_sq = (self.x-other.x) ** 2
        y_diff_sq = (self.y-other.y) ** 2
        return (x_diff_sq + y_diff_sq) ** 0.5
    
    def __str__(self):
        return("("+str(self.x)+", "+str(self.y)+")")

In [38]:
c = Coordinate(3, 4)
print(c)

(3, 4)


In [31]:
zero = Coordinate(0,0)
print(c.distance(zero))

5.0


In [17]:
print(Coordinate.distance(c, zero))

5.0


In [20]:
print(isinstance(zero, Coordinate))

True


In [34]:
zero.this_is_global = 5

In [39]:
print(Coordinate.this_is_global)
print(zero.this_is_global)
print(c.this_is_global)

10
5
10


## Numpy


In [ ]:
'''

#include <cmath>

using namespace std; 

int main()
{ int a;
cout<<"Hello";
cin>>a;
}


'''

In [42]:
# from numpy import *
# __version__

'1.18.1'

In [43]:
import numpy as np
np.__version__

'1.18.1'

In [44]:
np.__version__

'1.18.1'

In [ ]:
# Mention tab completion

In [47]:
?print

In [45]:
?np.__version__

In [56]:
test = np.array([1,2,3,4,5])
test2 = np.array([[1,2],[3,4]])

print(type(test), type(test2), test.shape, test2.shape)

<class 'numpy.ndarray'> <class 'numpy.ndarray'> (5,) (2, 2)


In [106]:
abc = np.array([1, 2, 3, 4], dtype='float32')
abc[0] = 100
print(abc)

[100.   2.   3.   4.]


In [109]:
sample = [1, 2, 3] + [4, 5, 6]
sample = np.array(sample)

In [50]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [51]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [52]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [53]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [55]:
test = [1, 2, 3, 4, 5]
print(test * 2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [57]:
print(test*2)

[ 2  4  6  8 10]


In [58]:
print(test + 4*test)

[ 5 10 15 20 25]


In [59]:
test3 = np.array([1,2,3,4,5], dtype=complex)

In [60]:
print("test3 =", test3)

print('test2 dtype =', test2.dtype)
# a = int(input())
test2 = test2.astype(np.uint8)

print('test2 dtype =', test2.dtype)

test3 = [1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]
test2 dtype = int64
test2 dtype = uint8


In [61]:
print('test3', test3)
# array[start:stop:skip]
print('test3[::2]', test3[::2])
print('test3[1::2]', test3[1::2])

test3 [1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]
test3[::2] [1.+0.j 3.+0.j 5.+0.j]
test3[1::2] [2.+0.j 4.+0.j]


In [62]:
print('test2', test2, sep="\n")
print('test2[1,1]', test2[1,1])
print('test2[1,:]', test2[1,:])
print('test2[:,1]', test2[:,1])

test2
[[1 2]
 [3 4]]
test2[1,1] 4
test2[1,:] [3 4]
test2[:,1] [2 4]


In [63]:
row_indices = [1, 2, 3]
print(test3[row_indices])

[2.+0.j 3.+0.j 4.+0.j]


In [64]:
A = np.array([[n+m*10 for n in range(5)] for m in range(5)])

print(A)

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]


In [69]:
x = np.ones((3, 5), dtype=float)

print("x ndim: ", x.ndim)
print("x shape:", x.shape)
print("x size: ", x.size)

x ndim:  2
x shape: (3, 5)
x size:  15


In [70]:
x.dtype

dtype('float64')

In [71]:
y = x #changes to y is reflected in x

y[0, :] = 0

print(x)

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [73]:
x = np.ones((3, 5), dtype=float)

y = x.copy()

y[0, :] = 0

print(x)
print(y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [77]:
x.reshape((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [78]:
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [79]:
x = x.reshape((5,3))

print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [80]:
# Speed test - bear in mind that list comprehensions are vectorised

def custom_dot(A, B):
  
  C = [[0 for i in range(len(B[0]))] for j in range(len(A))]
  
  for i in range(len(A)):
    for j in range(len(B[0])):
      C[i][j] = sum(A[i,:] * B[:,j])
  
  return C
    
%time using_numpy = np.dot(A,A)
%time raw_python = custom_dot(A,A)

CPU times: user 25 µs, sys: 4 µs, total: 29 µs
Wall time: 34.3 µs
CPU times: user 496 µs, sys: 0 ns, total: 496 µs
Wall time: 562 µs


In [81]:
big_array = np.random.rand(1000000) #million
%timeit sum(big_array)
%timeit np.sum(big_array)

790 µs ± 19.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
781 µs ± 18 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [82]:
%timeit min(big_array)
%timeit np.min(big_array)

183 ms ± 4.05 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
782 µs ± 8.27 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [84]:
M = np.mrando.random((3, 4))
print(M)

M.min(axis=0)

[[0.6995527  0.13809678 0.16113887 0.76049029]
 [0.29402321 0.90516315 0.9159076  0.23781331]
 [0.52491999 0.05422194 0.80872684 0.12709532]]


array([0.29402321, 0.05422194, 0.16113887, 0.12709532])

In [87]:
M.max(axis=1)

array([0.76049029, 0.9159076 , 0.80872684])

In [88]:
M.min()

0.054221939099628025

In [89]:
# Broadcasting - see ppt

a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b

array([5, 6, 7])

In [90]:
a + 5

array([5, 6, 7])

In [91]:
M = np.ones((3, 3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [92]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [110]:
# Sort
x = np.array([2, 1, 4, 3, 5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [94]:
i = np.argsort(x) #index of the sorted elements
print(i)

[1 0 3 2 4]


In [98]:
np.argmax(x), np.argmin(x)

(4, 1)

In [99]:
rand = np.random.RandomState(42)
X = rand.randint(0, 10, (4, 6))
print(X)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [100]:
# sort each column of X
np.sort(X, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [101]:
# sort each row of X
np.sort(X, axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

In [102]:
# argmax and argmin

a = np.array([[1,2,4,7], [9,88,6,45], [9,76,3,4]])

a

array([[ 1,  2,  4,  7],
       [ 9, 88,  6, 45],
       [ 9, 76,  3,  4]])

In [103]:
np.argmax(a)

5

In [104]:
np.argmax(a,axis=0)

array([1, 1, 1, 1])

In [105]:
np.argmax(a,axis=1)

array([3, 1, 1])

In [ ]:
np.argmin(a)

In [ ]:
np.argmin(a,axis=0)

In [ ]:
np.argmin(a,axis=1)

## That's it folks